### ISSUE TITLE
Can i get a full mask from one image

### ISSUE THREAD

**Issue by jzx-gooner** [spacewalk01/nanosam-cpp#2]
nice work!

Does this project support the image inference for get a mask like deeplabv3 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by spacewalk01** [comment]
The detected result is actually a binary mask for segmenting an object.
` auto mask = nanosam.predict(image, { promptPoint }, labels);`

For Example: 
![image](https://github.com/spacewalk01/nanosam-cpp/assets/6389915/d063f253-de63-46df-bd36-f1ae47f0fd8e)

**Comment by jzx-gooner** [comment]
![1](https://github.com/spacewalk01/nanosam-cpp/assets/29942202/13da4c58-13cb-4798-8c4e-a8395b5c0cf1)
like sam the everything method ， without promptpoint，it can get this mask picture

**Comment by spacewalk01** [comment]
It doesn't support everything method.

**Comment by jzx-gooner** [comment]
> It doesn't support everything method.

copy that and i will close this issue ，Many thanks for your repo！！！
